# Generated by Django 5.1 on 2024-09-20 05:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinTech', '0006_alter_expensecategory_name_alter_incomecategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=datetime.date(2024, 9, 20)),
        ),
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateField(default=datetime.date(2024, 9, 20)),
        ),
    ]
